### ISSUE TITLE
Twitch Alerts

### ISSUE THREAD

**Issue by brettmayson** [Synixe/Bot#29]
The old bot used to have twitch alerts when someone in @Active went live. Should we add that back in?

**Comment by namelessOwO** [comment]
No; No need to stalk our members

**Comment by brettmayson** [comment]
I'll do a poll to see if people are interested.

**Comment by namelessOwO** [comment]
god damn

**Comment by brettmayson** [comment]
Looks like the yays have it

**Comment by namelessOwO** [comment]
fine
